// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parser.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230625165550_AddColumns")]
    partial class AddColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Entities.Models.MetData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dataSource_title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dd_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dd_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ddavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ddavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ddmax_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ddmax_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diffSunRad_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diffSunRad_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diffSunRadavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diffSunRadavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("domain_altitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("domain_lat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("domain_lon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("domain_longTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("domain_meteosiId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("domain_shortTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("domain_title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ff_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ff_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ffavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ffavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ffmax_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ffmax_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gSunRad_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gSunRad_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gSunRadavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gSunRadavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hhs_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hhs_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("msl_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("msl_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mslavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mslavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nn_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ns_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ns_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("p_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("p_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("pavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rh_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rh_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rh_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rhavg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rhavg_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rhavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rhavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rr_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rr_val")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rr_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rr_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("snow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("snow_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("snow_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("snow_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sunrise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sunset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("t")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("t_5_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("t_5_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("t_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("t_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("t_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tavg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tavg_5_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tavg_5_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tavg_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tavg_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tavg_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("td")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("td_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("td_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("td_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_10_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_10_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_20_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_20_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_30_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_30_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_50_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_50_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_5_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tg_5_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_10_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_10_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_20_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_20_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_30_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_30_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_50_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_50_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_5_cm_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tgavg_5_cm_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tn_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tn_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_12h_acc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_12h_acc_state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_12h_acc_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_12h_acc_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_1h_acc_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_1h_acc_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_24h_acc_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tp_24h_acc_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsUpdated_RFC822")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsUpdated_UTC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsUpdated_day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsValid_issued")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsValid_issued_RFC822")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsValid_issued_UTC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tsValid_issued_day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tw_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tw_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tx_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tx_var_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("valid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("validEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("validStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("valid_UTC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("valid_day")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vis_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vis_unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("wwsyn_var_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MetData");
                });
#pragma warning restore 612, 618
        }
    }
}
